---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andreybevilacqua/SpringCloudConfigServer
          searchPaths: ConfigData
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001

# Control which Actuator web endpoints are exposed.
management:
  endpoints:
    web:
      exposure:
        include: health,info,bus-refresh